export const petMismatches = {
    Alchemedes: 'AlchemistBug',
    Burbel: 'Not found',
    'Cracked Egg': 'EggLadCracked',
    Clownfish: 'ClownFish',
    'Dirty Rat': 'Rat',
    Duckling: 'BabyDuck',
    Daycrawler: 'DayCrawler',
    'Lizard Tail': 'Lizard',
    'Loyal Chinchilla': 'Chinchilla',
    Monty: 'Not found',
    Murmel: 'Not found',
    'Nessie?': 'Nessie',
    'Young Phoenix': 'BabyPhoenix',
    'Smaller Slug': 'SlugToken',
    'Smallest Slug': 'SlugToken2',
    'Sneaky Egg': 'EggLadCovered',
    'Zombie Cricket': 'Cricket',
    'Zombie Fly': 'Fly',
    'Golden Beetle': 'Beetle',
    Mandrill: 'Drill',
    'Brain Cramp': 'HeadCrab',
    'Deer Lord': 'Deer',
    'Foo Dog': 'FuLion',
    'Fur-Bearing Trout': 'FurBearingTrout',
    Guineafowl: 'GuineaPig',
    Tree: 'TreeEnt',
    Abomination: 'Shoggoth',
    Cuttlefish: 'CuddleFish',
    Rootling: 'Rootler',
    Tahr: 'ArabianTahr',
    'Tiger Bug': 'Not found',
    Visitor: 'Xenomorph',
    'Worm of Sand': 'Sandworm',
    'Beluga Whale': 'WhiteWhale',
    Raccoon: 'Racoon',
    'Salmon of Knowledge': 'SalmonofWisdom',
    'Snapping Turtle': 'SnappingJawTurtle',
    Tandgnost: 'Not found',
    Tandgrisner: 'Not found',
    'Bird of Paradise': 'ParadiseBird',
    'German Shepherd': 'GermanShepard',
    'Great One': 'Cthulhu',
    'Hammerhead Shark': 'HammerShark',
    'Mantis Shrimp': 'ShrimpMantis',
    'Sting Ray': 'Stingray',
    Warf: 'Warg',
};

export const foodMismatches = {
    'Best Apple': 'Apple3',
    'Best Milk': 'Milk3',
    'Better Apple': 'Apple2',
    'Better Milk': 'Milk2',
    Blueberry: 'BlueBerries',
    Peach: 'Plumb',
    'Water of Youth': 'YouthWater',
    Cherry: 'Cherries',
    Cupcake: 'Not found',
    Rice: 'RiceBall',
    'Sleeping Pill': 'Pill',
    'Just-Right Porridge': 'JustRightPorridge',
    Lettuce: 'Salad',
    Donut: 'Doughnut',
    'Drink-Me Liquid': 'DrinkMeLiquid',
    'Eat-Me Cake': 'EatMeCake',
    'Best Chocolate': 'Chocolate3',
    'Better Chocolate': 'Chocolate2',
    Lasagna: 'Lasagne',
    Konpeito: 'Kompeito',
    'Peach of Immortality': 'ImmortalPeach',
};

export const toyMismatches = {
    'Yo-Yo': 'RelicYoYo',
    Spring: 'RelicSlinky',
    'Air Palm Tree': 'RelicPalmTree',
    'Stuffed Bear': 'RelicTeddyBear',
};
